version: "3.0"

services:
        mysql:
           build: .
           environment:
                   - MYSQL_ROOT_PASSWORD=R00t@123
           volumes:
                   - "/mysql/data2:/var/lib/mysql"
           ports:
             - "3306:3306"
